# -*- coding: utf-8 -*-
"""final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-EGivRbijAhyZi1MufTLQc2ILl8jMGa
"""

# Cell 1 - mount drive
from google.colab import drive
drive.mount('/content/drive')
!pip install shap xgboost statsmodels --quiet

# Cell 2 - import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import warnings
warnings.filterwarnings('ignore')

from scipy import stats
from scipy.stats import chi2
from statsmodels.stats.multitest import multipletests
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (roc_auc_score, roc_curve,
                              precision_recall_curve, average_precision_score)
from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import log_loss as sk_log_loss
from xgboost import XGBClassifier
import os

print("All imports successful")

# Cell 3 - loading csv files
folder_path = '/content/drive/MyDrive/project/'
output_dir  = '/content/drive/MyDrive/project/results/'
os.makedirs(output_dir, exist_ok=True)

metadata = pd.read_csv(folder_path + 'Source_Data_24Oct2022(subject_metadata).csv', encoding='latin1')
rel_ab   = pd.read_csv(folder_path + 'Source_Data_24Oct2022(metaphlan_rel_ab).csv', encoding='latin1')
pathway  = pd.read_csv(folder_path + 'Source_Data_24Oct2022(humann_pathway_counts).csv', encoding='latin1')

print("Metadata:", metadata.shape)
print("Rel abundance:", rel_ab.shape)
print("Pathway counts:", pathway.shape)

# Cell 4 - total count
# PD patients — depression label
pd_meta = metadata[metadata['Case_status'] == 'PD'].copy()
pd_meta['depression_label'] = (pd_meta['Depression_anxiety_mood_med'] == 'Y').astype(int)

# Healthy controls — depression label
ctrl_meta = metadata[metadata['Case_status'] == 'Control'].copy()
ctrl_meta['depression_label'] = (ctrl_meta['Depression_anxiety_mood_med'] == 'Y').astype(int)

# Full cohort — PD vs Control label
metadata['pd_label'] = (metadata['Case_status'] == 'PD').astype(int)

print(f"PD patients:  {len(pd_meta)} | Depressed: {pd_meta['depression_label'].sum()} ({pd_meta['depression_label'].mean():.1%})")
print(f"Controls:     {len(ctrl_meta)} | Depressed: {ctrl_meta['depression_label'].sum()} ({ctrl_meta['depression_label'].mean():.1%})")
print(f"Full cohort:  {len(metadata)} | PD: {metadata['pd_label'].sum()} ({metadata['pd_label'].mean():.1%})")

# Cell 5 - missing data report
meta_cols_check = [
    'Age_at_collection', 'Sex', 'BMI', 'Laxatives', 'Total_sequences',
    'Antibiotics_past_3_months', 'Probiotic', 'Pain_med', 'Sleep_aid',
    'Constipation', 'Do_you_smoke', 'Do_you_drink_caffeinated_beverages',
    'Do_you_drink_alcohol', 'Bristol_stool_chart', 'IBS', 'IBD',
    'Diarrhea', 'Blood_pressure_med', 'Cholesterol_med', 'Diabetes_med'
]
meta_cols_check = [c for c in meta_cols_check if c in metadata.columns]

print("MISSING DATA REPORT")

missing_report = pd.DataFrame({
    'column':        meta_cols_check,
    'missing_count': [metadata[c].isnull().sum() for c in meta_cols_check],
    'missing_pct':   [round(metadata[c].isnull().mean() * 100, 1) for c in meta_cols_check],
    'dtype':         [str(metadata[c].dtype) for c in meta_cols_check]
}).sort_values('missing_pct', ascending=False)
print(missing_report.to_string(index=False))

# No columns dropped - missing is less than 40%
drop_cols = missing_report[missing_report['missing_pct'] > 40]['column'].tolist()
meta_cols = [c for c in meta_cols_check if c not in drop_cols]
print(f"\nDropped (>40% missing): {drop_cols if drop_cols else 'None'}")
print(f"Columns kept for analysis: {len(meta_cols)}")

print("\nImputation strategy:")
print("  Numeric (BMI, Bristol_stool_chart): median imputation")
print("  Categorical Y/N columns: mode imputation then label encoding")


print("CLASS BALANCE REPORT")

print(f"PD depression:    Not depressed={( pd_meta['depression_label']==0).sum()} | Depressed={(pd_meta['depression_label']==1).sum()} | Ratio={(pd_meta['depression_label']==0).sum()/(pd_meta['depression_label']==1).sum():.2f}:1")
print(f"Ctrl depression:  Not depressed={(ctrl_meta['depression_label']==0).sum()} | Depressed={(ctrl_meta['depression_label']==1).sum()} | Ratio={(ctrl_meta['depression_label']==0).sum()/(ctrl_meta['depression_label']==1).sum():.2f}:1")
print(f"PD vs Control:    Controls={(metadata['pd_label']==0).sum()} | PD={(metadata['pd_label']==1).sum()} | Ratio={(metadata['pd_label']==1).sum()/(metadata['pd_label']==0).sum():.2f}:1")
print("\nImbalance handling: class_weight='balanced' in all sklearn models")
print("                    scale_pos_weight in XGBoost")
print("                    stratify=y in all train/test splits")

missing_report.to_csv(output_dir + 'missing_data_report.csv', index=False)

# Cell 6 - transformations
def clr_transform(df):
    X = df.copy().astype(float)
    X = X.replace(0, np.nan)
    delta = 0.65 * X.min(axis=1, skipna=True)
    for col in X.columns:
        X[col] = X[col].fillna(delta)
    log_X = np.log(X)
    clr = log_X.subtract(log_X.mean(axis=1), axis=0)
    return clr

def preprocess_microbiome_clr(df, prevalence=0.10):
    X = df.fillna(0)
    X = X.loc[:, (X > 0).mean(axis=0) >= prevalence]
    X = X.div(X.sum(axis=1), axis=0)
    X_clr = clr_transform(X)
    sel = VarianceThreshold(threshold=0.001)
    arr = sel.fit_transform(X_clr)
    return pd.DataFrame(arr, index=X_clr.index,
                        columns=X_clr.columns[sel.get_support()])

# Filter species-level rows and transpose
species_mask = (rel_ab['clade_name'].str.contains('s__') &
                ~rel_ab['clade_name'].str.contains('t__'))
rel_ab_sp = rel_ab[species_mask].copy()
rel_ab_sp['species_short'] = rel_ab_sp['clade_name'].str.split('|').str[-1]
rel_ab_sp = rel_ab_sp.set_index('species_short').drop(columns='clade_name')
rel_ab_T = rel_ab_sp.T
rel_ab_T.index.name = 'sample_name'
print(f"Full species matrix: {rel_ab_T.shape}")

# PD microbiome (CLR)
pd_micro_raw = rel_ab_T.loc[rel_ab_T.index.isin(pd_meta['sample_name'])]
X_pd = preprocess_microbiome_clr(pd_micro_raw)
y_pd = pd_meta.set_index('sample_name').loc[X_pd.index, 'depression_label'].values
feature_names = X_pd.columns.tolist()
print(f"PD microbiome (CLR):      {X_pd.shape} | Depression rate: {y_pd.mean():.1%}")

# Control microbiome (CLR) — same species as PD
ctrl_micro_raw = rel_ab_T.loc[rel_ab_T.index.isin(ctrl_meta['sample_name'])]
common_sp = [f for f in feature_names if f in ctrl_micro_raw.columns]
ctrl_micro_aligned = ctrl_micro_raw[common_sp].fillna(0)
ctrl_micro_aligned = ctrl_micro_aligned.div(ctrl_micro_aligned.sum(axis=1), axis=0)
X_ctrl = pd.DataFrame(clr_transform(ctrl_micro_aligned),
                      index=ctrl_micro_aligned.index, columns=common_sp)
y_ctrl = ctrl_meta.set_index('sample_name').loc[X_ctrl.index, 'depression_label'].values
print(f"Control microbiome (CLR): {X_ctrl.shape} | Depression rate: {y_ctrl.mean():.1%}")

# Full cohort microbiome (CLR) — PD vs Control classification
all_micro_raw = rel_ab_T.loc[rel_ab_T.index.isin(metadata['sample_name'])]
all_micro_aligned = all_micro_raw[common_sp].fillna(0)
all_micro_aligned = all_micro_aligned.div(all_micro_aligned.sum(axis=1), axis=0)
X_all_micro = pd.DataFrame(clr_transform(all_micro_aligned),
                            index=all_micro_aligned.index, columns=common_sp)
y_pd_label = metadata.set_index('sample_name').loc[X_all_micro.index, 'pd_label'].values
print(f"Full cohort microbiome (CLR): {X_all_micro.shape} | PD rate: {y_pd_label.mean():.1%}")

# Cell 7 - pathway proprocessing
def preprocess_pathway_clr(df_raw, sample_ids, prevalence=0.10):
    pathway_T = df_raw.set_index(df_raw.columns[0]).T
    pathway_T.index.name = 'sample_name'
    pathway_sub = pathway_T.loc[pathway_T.index.isin(sample_ids)].fillna(0)
    pathway_sub = pathway_sub.loc[:, (pathway_sub > 0).mean(axis=0) >= prevalence]
    pathway_sub = pathway_sub.div(pathway_sub.sum(axis=1), axis=0)
    pathway_clr = clr_transform(pathway_sub)
    sel = VarianceThreshold(threshold=0.001)
    arr = sel.fit_transform(pathway_clr)
    return arr, pathway_sub.index

# PD pathway — depression classification
X_path_pd, path_pd_idx = preprocess_pathway_clr(pathway, pd_meta['sample_name'])
y_path_pd = pd_meta.set_index('sample_name').loc[path_pd_idx, 'depression_label'].values
print(f"PD pathway (CLR):          {X_path_pd.shape} | Depression rate: {y_path_pd.mean():.1%}")

# Control pathway — depression classification
X_path_ctrl, path_ctrl_idx = preprocess_pathway_clr(pathway, ctrl_meta['sample_name'])
y_path_ctrl = ctrl_meta.set_index('sample_name').loc[path_ctrl_idx, 'depression_label'].values
print(f"Control pathway (CLR):     {X_path_ctrl.shape} | Depression rate: {y_path_ctrl.mean():.1%}")

# Full cohort pathway — PD vs Control classification
X_path_all, path_all_idx = preprocess_pathway_clr(pathway, metadata['sample_name'])
y_path_pd_label = metadata.set_index('sample_name').loc[path_all_idx, 'pd_label'].values
print(f"Full cohort pathway (CLR): {X_path_all.shape} | PD rate: {y_path_pd_label.mean():.1%}")

# Cell 8 — metadata preparation with imputation

if 'Total_sequences' in metadata.columns:
    pd_meta['Total_sequences_log']   = np.log1p(pd_meta['Total_sequences'])
    ctrl_meta['Total_sequences_log'] = np.log1p(ctrl_meta['Total_sequences'])
    metadata['Total_sequences_log']  = np.log1p(metadata['Total_sequences'])
    meta_cols = ['Total_sequences_log' if c == 'Total_sequences'
                 else c for c in meta_cols]
    print("Total_sequences log-transformed and replaced in feature list")
else:
    print("Total_sequences not found — skipping")

def prepare_metadata(meta_source, label_col, meta_cols):
    df = meta_source[['sample_name', label_col] + meta_cols].copy()
    df = df.set_index('sample_name')

    print(f"Class balance — Class 0: {(df[label_col]==0).sum()} | Class 1: {(df[label_col]==1).sum()}")

    numeric_cols   = df.drop(columns=label_col).select_dtypes(
        include=[np.number]).columns.tolist()
    categoric_cols = df.drop(columns=label_col).select_dtypes(
        exclude=[np.number]).columns.tolist()

    for col in numeric_cols:
        n_miss = df[col].isnull().sum()
        if n_miss > 0:
            print(f"  Imputing {col}: {n_miss} missing → median ({df[col].median():.2f})")
            df[col] = df[col].fillna(df[col].median())

    le = LabelEncoder()
    for col in categoric_cols:
        n_miss = df[col].isnull().sum()
        if n_miss > 0:
            mode_val = df[col].mode()[0]
            print(f"  Imputing {col}: {n_miss} missing → mode ({mode_val})")
            df[col] = df[col].fillna(mode_val)
        df[col] = le.fit_transform(df[col].astype(str))

    X = df.drop(columns=label_col).values
    y = df[label_col].values
    return X, y, df.drop(columns=label_col).columns.tolist()

# PD metadata — depression
print("\n PD Metadata for Depression Classification ")
X_meta_pd, y_meta_pd, meta_feature_names = prepare_metadata(
    pd_meta, 'depression_label', meta_cols)

# Control metadata — depression
print("\n Control Metadata for Depression Classification ")
X_meta_ctrl, y_meta_ctrl, _ = prepare_metadata(
    ctrl_meta, 'depression_label', meta_cols)

# Full cohort metadata — PD vs Control
print("\n Full Cohort Metadata for PD vs Control Classification ")
metadata_full = metadata.copy()
X_meta_all_pd, y_meta_all_pd, _ = prepare_metadata(
    metadata_full, 'pd_label', meta_cols)

print(f"\nMetadata features used: {meta_feature_names}")
print(f"Total metadata features: {len(meta_feature_names)}")

# Cell 9 — feature importance on metadata
from sklearn.feature_selection import SelectKBest, mutual_info_classif

sel_meta = SelectKBest(mutual_info_classif, k='all')
sel_meta.fit(X_meta_pd, y_meta_pd)

meta_importance = pd.DataFrame({
    'feature':     meta_feature_names,
    'mutual_info': sel_meta.scores_
}).sort_values('mutual_info', ascending=False)

print("Metadata feature importance ranked by mutual information:")
print(meta_importance.to_string(index=False))

meta_importance.to_csv(output_dir + 'metadata_feature_importance.csv', index=False)

# Plot
fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(meta_importance['feature'][::-1],
        meta_importance['mutual_info'][::-1],
        color='steelblue')
ax.set_xlabel('Mutual Information Score')
ax.set_title('Metadata Feature Importance — Mutual Information\n(PD Depression Classification)')
plt.tight_layout()
plt.savefig(output_dir + 'metadata_importance.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 10 - statistical analysis
p_values    = []
odds_ratios = []

for col in X_pd.columns:
    x = X_pd[col].values.reshape(-1, 1)
    lr = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
    lr.fit(x, y_pd)
    odds_ratio = np.exp(lr.coef_[0][0])

    null_prob  = np.full(len(y_pd), y_pd.mean())
    null_loss  = sk_log_loss(y_pd, null_prob)
    model_loss = sk_log_loss(y_pd, lr.predict_proba(x)[:, 1])
    lr_stat    = 2 * len(y_pd) * (null_loss - model_loss)
    p          = 1 - chi2.cdf(lr_stat, df=1)

    p_values.append(p)
    odds_ratios.append(odds_ratio)

reject, p_adj, _, _ = multipletests(p_values, method='fdr_bh')

stats_results = pd.DataFrame({
    'species':     feature_names,
    'odds_ratio':  odds_ratios,
    'p_value':     p_values,
    'p_adjusted':  p_adj,
    'significant': reject
}).sort_values('p_adjusted')

print(f"Significant species (FDR < 0.05): {reject.sum()}")
print("\nTop significant species:")
print(stats_results[stats_results['significant']].head(20).to_string(index=False))
stats_results.to_csv(output_dir + 'statistical_analysis.csv', index=False)

# Cell 11 - function definition
def run_experiment(X_data, y_data, experiment_name):
    print(f"EXPERIMENT: {experiment_name}")
    print(f"Samples: {len(y_data)} | Positive rate: {y_data.mean():.1%}")
    print(f"Class balance: {(y_data==0).sum()} class-0 | {(y_data==1).sum()} class-1")
    print(f"{'-'*65}")

    if y_data.sum() < 10 or (len(y_data) - y_data.sum()) < 10:
        print("Insufficient class samples — skipping.")
        return None

    X_tv, X_te, y_tv, y_te = train_test_split(
        X_data, y_data, test_size=0.20, random_state=42, stratify=y_data)
    X_tr, X_v, y_tr, y_v   = train_test_split(
        X_tv, y_tv, test_size=0.25, random_state=42, stratify=y_tv)

    scaler = StandardScaler()
    X_tr_s = scaler.fit_transform(X_tr)
    X_te_s = scaler.transform(X_te)

    spw = (y_tr==0).sum() / (y_tr==1).sum()

    models = {
        'Logistic Regression': LogisticRegression(
            penalty='l1', solver='liblinear', C=0.1,
            class_weight='balanced', random_state=42, max_iter=1000),
        'Random Forest': RandomForestClassifier(
            n_estimators=200, max_depth=10,
            class_weight='balanced', random_state=42, n_jobs=-1),
        'SVM': SVC(
            kernel='rbf', C=1.0, probability=True,
            class_weight='balanced', random_state=42),
        'XGBoost': XGBClassifier(
            n_estimators=200, max_depth=5, learning_rate=0.05,
            scale_pos_weight=spw,
            random_state=42, eval_metric='logloss', verbosity=0),
        'MLP': MLPClassifier(
            hidden_layer_sizes=(128, 64), activation='relu',
            max_iter=500, random_state=42, early_stopping=True)
    }

    results = {}
    for name, model in models.items():
        model.fit(X_tr_s, y_tr)
        auc = roc_auc_score(y_te, model.predict_proba(X_te_s)[:, 1])
        results[name] = round(auc, 4)
        print(f"  {name}: AUC = {auc:.4f}")

    return results

all_results = {}

# Cell 12 — Experiment 1: Classifying Parkinson's from Microbiome Data
all_results['Exp 1: PD vs Control — Microbiome'] = run_experiment(
    X_all_micro.values, y_pd_label,
    "Experiment 1 — Classifying Parkinson's from Microbiome Data")

# Cell 13 — Experiment 2: Classifying Parkinson's from Pathway Abundance
all_results['Exp 2: PD vs Control — Pathway'] = run_experiment(
    X_path_all, y_path_pd_label,
    "Experiment 2 — Classifying Parkinson's from Pathway Abundance")

# Cell 14 — Experiment 3: Classifying Parkinson's from Metadata
all_results['Exp 3: PD vs Control — Metadata'] = run_experiment(
    X_meta_all_pd, y_meta_all_pd,
    "Experiment 3 — Classifying Parkinson's from Metadata")

# Cell 15 — Experiment 4: Classifying Depression in PD from Microbiome Data
all_results['Exp 4: PD Depression — Microbiome'] = run_experiment(
    X_pd.values, y_pd,
    "Experiment 4 — Classifying Depression in PD from Microbiome Data")

# Cell 16 — Experiment 5: Classifying Depression in PD from Pathway Abundance
all_results['Exp 5: PD Depression — Pathway'] = run_experiment(
    X_path_pd, y_path_pd,
    "Experiment 5 — Classifying Depression in PD from Pathway Abundance")

# Cell 17 — Experiment 6: Classifying Depression in PD from Metadata
all_results['Exp 6: PD Depression — Metadata'] = run_experiment(
    X_meta_pd, y_meta_pd,
    "Experiment 6 — Classifying Depression in PD from Metadata")

# Cell 18 — Experiment 7: Classifying Depression in Healthy Controls from Microbiome Data
all_results['Exp 7: Ctrl Depression — Microbiome'] = run_experiment(
    X_ctrl.values, y_ctrl,
    "Experiment 7 — Classifying Depression in Healthy Controls from Microbiome Data")

# Cell 19 — Experiment 8: Classifying Depression in Healthy Controls from Pathway Abundance
all_results['Exp 8: Ctrl Depression — Pathway'] = run_experiment(
    X_path_ctrl, y_path_ctrl,
    "Experiment 8 — Classifying Depression in Healthy Controls from Pathway Abundance")

# Cell 20 — Experiment 9: Classifying Depression in Healthy Controls from Metadata
all_results['Exp 9: Ctrl Depression — Metadata'] = run_experiment(
    X_meta_ctrl, y_meta_ctrl,
    "Experiment 9 — Classifying Depression in Healthy Controls from Metadata")

# Cell 21 — Experiment 10: All 5 models trained on PD, tested on controls
scaler_f = StandardScaler()
X_pd_s   = scaler_f.fit_transform(X_pd.values)
X_ctrl_s = scaler_f.transform(X_ctrl.values)

exp10_results = {}
for name, m in {
    'Logistic Regression': LogisticRegression(penalty='l1', solver='liblinear',
        C=0.1, class_weight='balanced', random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=200,
        class_weight='balanced', random_state=42),
    'SVM': SVC(kernel='rbf', C=1.0, probability=True,
        class_weight='balanced', random_state=42),
    'XGBoost': XGBClassifier(verbosity=0, random_state=42,
        eval_metric='logloss'),
    'MLP': MLPClassifier(hidden_layer_sizes=(128,64), max_iter=500,
        random_state=42, early_stopping=True)
}.items():
    m.fit(X_pd_s, y_pd)
    auc = roc_auc_score(y_ctrl, m.predict_proba(X_ctrl_s)[:, 1])
    exp10_results[name] = round(auc, 4)
    print(f"  {name}: AUC = {auc:.4f}")

all_results['Exp 10: PD->Ctrl Generalisation'] = exp10_results

# Cell 22 — Experiment 11: Microbiome and Metadata Combined for Depression in PD
common_idx = X_pd.index.intersection(
    pd_meta.set_index('sample_name').index)

X_micro_al = X_pd.loc[common_idx].values

X_meta_al  = pd_meta.set_index('sample_name').loc[common_idx, meta_cols].copy()
for col in X_meta_al.columns:
    if X_meta_al[col].dtype == object:
        X_meta_al[col] = LabelEncoder().fit_transform(
            X_meta_al[col].astype(str))
X_meta_al  = X_meta_al.fillna(X_meta_al.median()).values

y_combined = pd_meta.set_index('sample_name').loc[
    common_idx, 'depression_label'].values
X_combined = np.hstack([X_micro_al, X_meta_al])

print(f"Combined matrix shape: {X_combined.shape}")
print(f"  Microbiome features: {X_micro_al.shape[1]}")
print(f"  Metadata features:   {X_meta_al.shape[1]}")

all_results['Exp 11: PD Depression — Micro+Meta'] = run_experiment(
    X_combined, y_combined,
    "Experiment 11 — Microbiome and Metadata Combined for Depression in PD")

# Cell 23 — Experiment 12: All Three Feature Types Combined for Depression in PD
common_idx_l = X_pd.index.intersection(
    pd.Index(path_pd_idx)).intersection(
    pd_meta.set_index('sample_name').index)

X_micro_l = X_pd.loc[common_idx_l].values

X_path_l  = pd.DataFrame(
    X_path_pd, index=path_pd_idx
).reindex(common_idx_l).fillna(0).values

X_meta_l  = pd_meta.set_index('sample_name').loc[common_idx_l, meta_cols].copy()
for col in X_meta_l.columns:
    if X_meta_l[col].dtype == object:
        X_meta_l[col] = LabelEncoder().fit_transform(
            X_meta_l[col].astype(str))
X_meta_l  = X_meta_l.fillna(X_meta_l.median()).values

y_triple  = pd_meta.set_index('sample_name').loc[
    common_idx_l, 'depression_label'].values
X_triple  = np.hstack([X_micro_l, X_path_l, X_meta_l])

print(f"Triple combined matrix shape: {X_triple.shape}")
print(f"  Microbiome features: {X_micro_l.shape[1]}")
print(f"  Pathway features:    {X_path_l.shape[1]}")
print(f"  Metadata features:   {X_meta_l.shape[1]}")

all_results['Exp 12: PD Depression — All Features'] = run_experiment(
    X_triple, y_triple,
    "Experiment 12 — All Three Feature Types Combined for Depression in PD")

# Cell 24 — master AUC table
summary_table = pd.DataFrame(all_results).T
print("MASTER AUC COMPARISON TABLE")

print(summary_table.to_string())
summary_table.to_csv(output_dir + 'master_auc_table.csv')

# Cell 25 — AUC bar chart
fig, ax = plt.subplots(figsize=(20, 7))
summary_table.astype(float).plot(kind='bar', ax=ax, width=0.75)
ax.axhline(0.5, color='red', linestyle='--', linewidth=1.5, label='Random chance (0.5)')
ax.set_title('ROC-AUC Across All 12 Experiments and 5 Models',
             fontsize=13, fontweight='bold')
ax.set_ylabel('ROC-AUC')
ax.set_ylim(0.3, 1.0)
ax.legend(bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=8)
plt.xticks(rotation=35, ha='right', fontsize=9)
plt.tight_layout()
plt.savefig(output_dir + 'master_auc_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 26 — AUC heatmap
fig, ax = plt.subplots(figsize=(10, 8))
heatmap_data = summary_table.astype(float)

sns.heatmap(
    heatmap_data,
    annot=True,
    fmt='.3f',
    cmap='RdYlGn',
    vmin=0.45,
    vmax=0.80,
    ax=ax,
    linewidths=0.5,
    linecolor='white',
    cbar_kws={'label': 'ROC-AUC'}
)
ax.set_title('AUC Heatmap — All 12 Experiments × 5 Models',
             fontsize=12, fontweight='bold')
plt.xticks(rotation=30, ha='right', fontsize=9)
plt.yticks(rotation=0, fontsize=9)
plt.tight_layout()
plt.savefig(output_dir + 'auc_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 27 — precision-recall curves
X_tr2, X_te2, y_tr2, y_te2 = train_test_split(
    X_pd.values, y_pd, test_size=0.2, random_state=42, stratify=y_pd)
sc2    = StandardScaler()
X_tr2s = sc2.fit_transform(X_tr2)
X_te2s = sc2.transform(X_te2)

fig, ax = plt.subplots(figsize=(9, 6))
for name, m in {
    'Logistic Regression': LogisticRegression(penalty='l1', solver='liblinear',
        C=0.1, class_weight='balanced', random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=200,
        class_weight='balanced', random_state=42),
    'SVM': SVC(kernel='rbf', probability=True,
        class_weight='balanced', random_state=42),
    'XGBoost': XGBClassifier(verbosity=0, random_state=42,
        eval_metric='logloss'),
    'MLP': MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=500,
        random_state=42, early_stopping=True)
}.items():
    m.fit(X_tr2s, y_tr2)
    probs = m.predict_proba(X_te2s)[:, 1]
    prec, rec, _ = precision_recall_curve(y_te2, probs)
    ap = average_precision_score(y_te2, probs)
    ax.plot(rec, prec, label=f'{name} (AP={ap:.3f})')

ax.axhline(y_pd.mean(), color='red', linestyle='--',
           label=f'Baseline ({y_pd.mean():.2f})')
ax.set_xlabel('Recall')
ax.set_ylabel('Precision')
ax.set_title('Precision-Recall Curves — Experiment 4 (PD Depression, Microbiome CLR)')
ax.legend(fontsize=9)
plt.tight_layout()
plt.savefig(output_dir + 'precision_recall_curves.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 28 — bootstrap statistical comparison
def bootstrap_compare(y_true, probs1, probs2, name1, name2, n=1000):
    diffs = []
    rng = np.random.default_rng(42)
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            diffs.append(roc_auc_score(y_true[idx], probs1[idx]) -
                         roc_auc_score(y_true[idx], probs2[idx]))
        except: pass
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    print(f"{name1} vs {name2}: diff={np.mean(diffs):.4f}, "
          f"95%CI=[{lo:.4f},{hi:.4f}], Sig={'YES' if lo > 0 else 'NO'}")

X_tr3, X_te3, y_tr3, y_te3 = train_test_split(
    X_pd.values, y_pd, test_size=0.2, random_state=42, stratify=y_pd)
sc3    = StandardScaler()
X_tr3s = sc3.fit_transform(X_tr3)
X_te3s = sc3.transform(X_te3)

trained = {}
for name, m in {
    'SVM': SVC(kernel='rbf', probability=True,
        class_weight='balanced', random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=200,
        class_weight='balanced', random_state=42),
    'Logistic Regression': LogisticRegression(penalty='l1',
        solver='liblinear', C=0.1, class_weight='balanced',
        random_state=42, max_iter=1000),
    'XGBoost': XGBClassifier(verbosity=0, random_state=42,
        eval_metric='logloss'),
    'MLP': MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=500,
        random_state=42, early_stopping=True)
}.items():
    m.fit(X_tr3s, y_tr3)
    trained[name] = m.predict_proba(X_te3s)[:, 1]
    print(f"{name}: AUC = {roc_auc_score(y_te3, trained[name]):.4f}")

print("\nPairwise bootstrap comparisons:")
names = list(trained.keys())
for i in range(len(names)):
    for j in range(i+1, len(names)):
        bootstrap_compare(y_te3, trained[names[i]],
                          trained[names[j]], names[i], names[j])

# Cell 29 — SHAP and LASSO feature importance
X_tr4, X_te4, y_tr4, y_te4 = train_test_split(
    X_pd.values, y_pd, test_size=0.2, random_state=42, stratify=y_pd)
sc4    = StandardScaler()
X_tr4s = sc4.fit_transform(X_tr4)
X_te4s = sc4.transform(X_te4)

# LASSO coefficients
lr4 = LogisticRegression(penalty='l1', solver='liblinear', C=0.1,
                          class_weight='balanced', random_state=42,
                          max_iter=1000)
lr4.fit(X_tr4s, y_tr4)
coef_df = pd.DataFrame({'species': feature_names,
                        'coefficient': lr4.coef_[0]})
coef_df = coef_df[coef_df['coefficient'] != 0].sort_values(
    'coefficient', key=abs, ascending=False)
top20   = coef_df.head(20)

plt.figure(figsize=(11, 7))
plt.barh(top20['species'], top20['coefficient'],
         color=['red' if c > 0 else 'steelblue' for c in top20['coefficient']])
plt.xlabel('LASSO Coefficient')
plt.title('Top Predictive Species — LASSO (CLR)\n'
          'Red = higher in depressed | Blue = lower in depressed')
plt.tight_layout()
plt.savefig(output_dir + 'lasso_coefficients.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"Non-zero species selected by LASSO: {len(coef_df)}")
coef_df.to_csv(output_dir + 'lasso_coefficients.csv', index=False)

# SHAP — Random Forest
rf4 = RandomForestClassifier(n_estimators=200, max_depth=10,
                              class_weight='balanced', random_state=42,
                              n_jobs=-1)
rf4.fit(X_tr4s, y_tr4)
explainer = shap.TreeExplainer(rf4)
shap_vals = explainer.shap_values(X_te4s)
sv        = shap_vals[1] if isinstance(shap_vals, list) else shap_vals
sv_flat   = sv if sv.ndim == 2 else sv[:, :, 1]

plt.figure(figsize=(11, 8))
shap.summary_plot(sv_flat, X_te4s, feature_names=feature_names,
                  max_display=20, show=False)
plt.title('SHAP Feature Importance — Random Forest (CLR)')
plt.tight_layout()
plt.savefig(output_dir + 'shap_rf.png', dpi=150, bbox_inches='tight')
plt.show()

# SHAP — XGBoost
xgb4 = XGBClassifier(n_estimators=200, max_depth=5, learning_rate=0.05,
                      random_state=42, eval_metric='logloss', verbosity=0)
xgb4.fit(X_tr4s, y_tr4)
explainer_xgb = shap.TreeExplainer(xgb4)
shap_xgb      = explainer_xgb.shap_values(X_te4s)

plt.figure(figsize=(11, 8))
shap.summary_plot(shap_xgb, X_te4s, feature_names=feature_names,
                  max_display=20, show=False)
plt.title('SHAP Feature Importance — XGBoost (CLR)')
plt.tight_layout()
plt.savefig(output_dir + 'shap_xgb.png', dpi=150, bbox_inches='tight')
plt.show()

pd.DataFrame({
    'species': feature_names,
    'mean_abs_shap': np.abs(sv_flat).mean(axis=0)
}).sort_values('mean_abs_shap', ascending=False).to_csv(
    output_dir + 'shap_importance_rf.csv', index=False)

# Cell 30 — metadata analysis plots
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
dep_g     = pd_meta[pd_meta['depression_label'] == 1]
not_dep_g = pd_meta[pd_meta['depression_label'] == 0]

axes[0].hist([dep_g['Age_at_collection'], not_dep_g['Age_at_collection']],
             bins=20, label=['Depressed', 'Not Depressed'],
             alpha=0.7, color=['salmon', 'steelblue'])
_, p_age = stats.mannwhitneyu(dep_g['Age_at_collection'],
                               not_dep_g['Age_at_collection'])
axes[0].set_title(f'Age Distribution (p={p_age:.4f})')
axes[0].set_xlabel('Age')
axes[0].legend()

sex_tab = pd.crosstab(pd_meta['Sex'], pd_meta['depression_label'])
sex_tab.plot(kind='bar', ax=axes[1], color=['steelblue', 'salmon'])
_, p_sex, _, _ = stats.chi2_contingency(sex_tab)
axes[1].set_title(f'Sex by Depression (p={p_sex:.4f})')
axes[1].set_xticklabels(['Female', 'Male'], rotation=0)
axes[1].legend(['Not Depressed', 'Depressed'])

pd_meta['depression_label'].value_counts().sort_index().plot(
    kind='bar', ax=axes[2], color=['steelblue', 'salmon'])
axes[2].set_title('Depression Status in PD Cohort')
axes[2].set_xticklabels(['Not Depressed', 'Depressed'], rotation=0)
axes[2].set_ylabel('Count')

plt.tight_layout()
plt.savefig(output_dir + 'metadata_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 31 — experiment plan diagram
plan = pd.DataFrame({
    'Exp No.': [f'Exp {i}' for i in range(1, 13)],
    'Experiment': [
        "Classifying Parkinson's from Microbiome Data",
        "Classifying Parkinson's from Pathway Abundance",
        "Classifying Parkinson's from Metadata",
        'Classifying Depression in PD from Microbiome Data',
        'Classifying Depression in PD from Pathway Abundance',
        'Classifying Depression in PD from Metadata',
        'Classifying Depression in Healthy Controls from Microbiome Data',
        'Classifying Depression in Healthy Controls from Pathway Abundance',
        'Classifying Depression in Healthy Controls from Metadata',
        'Does PD Depression Model Generalise to Healthy Controls',
        'Microbiome and Metadata Combined for Depression in PD',
        'All Three Feature Types Combined for Depression in PD'
    ],
    'Dataset': [
        'Full cohort', 'Full cohort', 'Full cohort',
        'PD only', 'PD only', 'PD only',
        'Controls only', 'Controls only', 'Controls only',
        'Train: PD / Test: Controls',
        'PD only', 'PD only'
    ],
    'Features': [
        'Microbiome CLR', 'Pathway CLR', 'Metadata',
        'Microbiome CLR', 'Pathway CLR', 'Metadata',
        'Microbiome CLR', 'Pathway CLR', 'Metadata',
        'Microbiome CLR',
        'Microbiome CLR + Metadata',
        'Microbiome CLR + Pathway CLR + Metadata'
    ]
})

fig, ax = plt.subplots(figsize=(20, 5))
ax.axis('off')
tbl = ax.table(cellText=plan.values, colLabels=plan.columns,
               cellLoc='left', loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(8)
tbl.auto_set_column_width(col=list(range(len(plan.columns))))
for (r, c), cell in tbl.get_celld().items():
    if r == 0:
        cell.set_facecolor('#2c3e50')
        cell.set_text_props(color='white', fontweight='bold')
    elif r % 2 == 0:
        cell.set_facecolor('#f2f2f2')
plt.title('Experiment Plan — All 12 Experiments',
          fontsize=12, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(output_dir + 'experiment_plan.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 32 — ROC curves
fig, ax = plt.subplots(figsize=(8, 6))
for name, probs in trained.items():
    fpr, tpr, _ = roc_curve(y_te3, probs)
    auc = roc_auc_score(y_te3, probs)
    ax.plot(fpr, tpr, label=f'{name} (AUC={auc:.3f})')
ax.plot([0, 1], [0, 1], 'k--', label='Random chance')
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.set_title('ROC Curves — Experiment 4: PD Depression, Microbiome CLR')
ax.legend(fontsize=9)
plt.tight_layout()
plt.savefig(output_dir + 'roc_curves.png', dpi=150, bbox_inches='tight')
plt.show()

# Cell 33 — Saving all results
summary_table.to_csv(output_dir + 'master_auc_table.csv')
stats_results.to_csv(output_dir + 'statistical_analysis.csv', index=False)
coef_df.to_csv(output_dir + 'lasso_coefficients.csv', index=False)
missing_report.to_csv(output_dir + 'missing_data_report.csv', index=False)
plan.to_csv(output_dir + 'experiment_plan.csv', index=False)

print("All results saved to Drive.")
print(os.listdir(output_dir))

